bairros_manaus = [
    ("ADRIANÓPOLIS", "ADRIANÓPOLIS"),
    ("AJURICABA", "AJURICABA"),
    ("ALEIXO", "ALEIXO"),
    ("ALFREDO NASCIMENTO", "ALFREDO NASCIMENTO"),
    ("ALIANÇA COM DEUS", "ALIANÇA COM DEUS"),
    ("ALVORADA", "ALVORADA"),
    ("ALVORADA II", "ALVORADA II"),
    ("ALVORADA III", "ALVORADA III"),
    ("AMAZONINO MENDES", "AMAZONINO MENDES"),
    ("AMINE LINDOSO", "AMINE LINDOSO"),
    ("APARECIDA", "APARECIDA"),
    ("ÁREA RURAL", "ÁREA RURAL"),
    ("ARMANDO MENDES", "ARMANDO MENDES"),
    ("BAIRRO DA PAZ", "BAIRRO DA PAZ"),
    ("BETÂNIA", "BETÂNIA"),
    ("BRASILEIRINHO", "BRASILEIRINHO"),
    ("CACHOEIRINHA", "CACHOEIRINHA"),
    ("CENTRO", "CENTRO"),
    ("CHAPADA", "CHAPADA"),
    ("CIDADE DE DEUS", "CIDADE DE DEUS"),
    ("CIDADE NOVA", "CIDADE NOVA"),
    ("COLÔNIA ANTÔNIO ALEIXO", "COLÔNIA ANTÔNIO ALEIXO"),
    ("COLÔNIA CHICO MENDES", "COLÔNIA CHICO MENDES"),
    ("COLÔNIA OLIVEIRA MACHADO", "COLÔNIA OLIVEIRA MACHADO"),
    ("COLÔNIA SANTO ANTÔNIO", "COLÔNIA SANTO ANTÔNIO"),
    ("COLÔNIA TERRA NOVA", "COLÔNIA TERRA NOVA"),
    ("COLÔNIA TERRA NOVA III", "COLÔNIA TERRA NOVA III"),
    ("COMPENSA", "COMPENSA"),
    ("CONJUNTO FRANCISCA MENDES", "CONJUNTO FRANCISCA MENDES"),
    ("CONJUNTO JURUA", "CONJUNTO JURUA"),
    ("CONJUNTO KYSSIA", "CONJUNTO KYSSIA"),
    ("CONJUNTO MARINA TAUÁ", "CONJUNTO MARINA TAUÁ"),
    ("COROADO", "COROADO"),
    ("CRESPO", "CRESPO"),
    ("DISTRITO INDUSTRIAL", "DISTRITO INDUSTRIAL"),
    ("DISTRITO INDUSTRIAL II", "DISTRITO INDUSTRIAL II"),
    ("DOM PEDRO", "DOM PEDRO"),
    ("DOM PEDRO II", "DOM PEDRO II"),
    ("EDUCANDOS", "EDUCANDOS"),
    ("FLORES", "FLORES"),
    ("GILBERTO MESTRINHO", "GILBERTO MESTRINHO"),
    ("GLÓRIA", "GLÓRIA"),
    ("GRANDE VITÓRIA", "GRANDE VITÓRIA"),
    ("INTERIOR DO ESTADO", "INTERIOR DO ESTADO"),
    ("JAPIIM", "JAPIIM"),
    ("JOÃO PAULO II", "JOÃO PAULO II"),
    ("JORGE TEIXEIRA", "JORGE TEIXEIRA"),
    ("LAGO AZUL", "LAGO AZUL"),
    ("LÍRIO DO VALE", "LÍRIO DO VALE"),
    ("LOTEAMENTO NOVO ALEIXO", "LOTEAMENTO NOVO ALEIXO"),
    ("MAUAZINHO", "MAUAZINHO"),
    ("MONTE DAS OLIVEIRAS", "MONTE DAS OLIVEIRAS"),
    ("MONTE SINAI", "MONTE SINAI"),
    ("MORADA DO SOL", "MORADA DO SOL"),
    ("MORRO DA LIBERDADE", "MORRO DA LIBERDADE"),
    ("NOSSA SENHORA APARECIDA", "NOSSA SENHORA APARECIDA"),
    ("NOSSA SENHORA DAS GRAÇAS", "NOSSA SENHORA DAS GRAÇAS"),
    ("NOSSA SENHORA DE FÁTIMA", "NOSSA SENHORA DE FÁTIMA"),
    ("NOVA CIDADE", "NOVA CIDADE"),
    ("NOVA CONQUISTA", "NOVA CONQUISTA"),
    ("NOVA ESPERANÇA", "NOVA ESPERANÇA"),
    ("NOVA FLORESTA", "NOVA FLORESTA"),
    ("NOVA VITORIA", "NOVA VITORIA"),
    ("NOVO ALEIXO", "NOVO ALEIXO"),
    ("NOVO ISRAEL", "NOVO ISRAEL"),
    ("OUTRA UF", "OUTRA UF"),
    ("PARQUE DAS LARANJEIRAS", "PARQUE DAS LARANJEIRAS"),
    ("PARQUE DEZ DE NOVEMBRO", "PARQUE DEZ DE NOVEMBRO"),
    ("PETRÓPOLIS", "PETRÓPOLIS"),
    ("PLANALTO", "PLANALTO"),
    ("PONTA NEGRA", "PONTA NEGRA"),
    ("PRAÇA 14 DE JANEIRO", "PRAÇA 14 DE JANEIRO"),
    ("PRESIDENTE VARGAS", "PRESIDENTE VARGAS"),
    ("PURAQUEQUARA", "PURAQUEQUARA"),
    ("RAIZ", "RAIZ"),
    ("REDENÇÃO", "REDENÇÃO"),
    ("RIACHO DOCE", "RIACHO DOCE"),
    ("SANTA ETELVINA", "SANTA ETELVINA"),
    ("SANTA LUZIA", "SANTA LUZIA"),
    ("SANTO AGOSTINHO", "SANTO AGOSTINHO"),
    ("SANTO ANTÔNIO", "SANTO ANTÔNIO"),
    ("SÃO FRANCISCO", "SÃO FRANCISCO"),
    ("SÃO GERALDO", "SÃO GERALDO"),
    ("SÃO JORGE", "SÃO JORGE"),
    ("SÃO JOSÉ", "SÃO JOSÉ"),
    ("SÃO LÁZARO", "SÃO LÁZARO"),
    ("SÃO RAIMUNDO", "SÃO RAIMUNDO"),
    ("TANCREDO NEVES", "TANCREDO NEVES"),
    ("TARUMÃ", "TARUMÃ"),
    ("UNIÃO", "UNIÃO"),
    ("VIEIRALVES", "VIEIRALVES"),
    ("VILA BURITI", "VILA BURITI"),
    ("VILA DA PRATA", "VILA DA PRATA"),
    ("ZONA RURAL", "ZONA RURAL"),
    ("ZUMBI DOS PALMARES", "ZUMBI DOS PALMARES"),
]

cidades_amazonas = [
    ("Alvarães", "Alvarães"),
    ("Amaturá", "Amaturá"),
    ("Anamã", "Anamã"),
    ("Anori", "Anori"),
    ("Apuí", "Apuí"),
    ("Atalaia do Norte", "Atalaia do Norte"),
    ("Autazes", "Autazes"),
    ("Barcelos", "Barcelos"),
    ("Barreirinha", "Barreirinha"),
    ("Benjamin Constant", "Benjamin Constant"),
    ("Beruri", "Beruri"),
    ("Boa Vista do Ramos", "Boa Vista do Ramos"),
    ("Boca do Acre", "Boca do Acre"),
    ("Borba", "Borba"),
    ("Caapiranga", "Caapiranga"),
    ("Canutama", "Canutama"),
    ("Carauari", "Carauari"),
    ("Careiro", "Careiro"),
    ("Careiro da Várzea", "Careiro da Várzea"),
    ("Coari", "Coari"),
    ("Codajás", "Codajás"),
    ("Eirunepé", "Eirunepé"),
    ("Envira", "Envira"),
    ("Fonte Boa", "Fonte Boa"),
    ("Guajará", "Guajará"),
    ("Humaitá", "Humaitá"),
    ("Ipixuna", "Ipixuna"),
    ("Iranduba", "Iranduba"),
    ("Itacoatiara", "Itacoatiara"),
    ("Itamarati", "Itamarati"),
    ("Itapiranga", "Itapiranga"),
    ("Japurá", "Japurá"),
    ("Juruá", "Juruá"),
    ("Jutaí", "Jutaí"),
    ("Lábrea", "Lábrea"),
    ("Manacapuru", "Manacapuru"),
    ("Manaquiri", "Manaquiri"),
    ("Manaus", "Manaus"),
    ("Manicoré", "Manicoré"),
    ("Maraã", "Maraã"),
    ("Maués", "Maués"),
    ("Nhamundá", "Nhamundá"),
    ("Nova Olinda do Norte", "Nova Olinda do Norte"),
    ("Novo Airão", "Novo Airão"),
    ("Novo Aripuanã", "Novo Aripuanã"),
    ("Parintins", "Parintins"),
    ("Pauini", "Pauini"),
    ("Presidente Figueiredo", "Presidente Figueiredo"),
    ("Rio Preto da Eva", "Rio Preto da Eva"),
    ("Santa Isabel do Rio Negro", "Santa Isabel do Rio Negro"),
    ("Santo Antônio do Içá", "Santo Antônio do Içá"),
    ("São Gabriel da Cachoeira", "São Gabriel da Cachoeira"),
    ("São Paulo de Olivença", "São Paulo de Olivença"),
    ("São Sebastião do Uatumã", "São Sebastião do Uatumã"),
    ("Silves", "Silves"),
    ("Tabatinga", "Tabatinga"),
    ("Tapauá", "Tapauá"),
    ("Tefé", "Tefé"),
    ("Tonantins", "Tonantins"),
    ("Uarini", "Uarini"),
    ("Urucará", "Urucará"),
    ("Urucurituba", "Urucurituba"),
]
